export const BASE_URL = 'https://3a56-182-0-198-146.ap.ngrok.io/annida'
export const REGISTER = '/registration'
export const MONITORING = '/monitoring/registration'
export const RELIGION = '/religion'
export const SCHOOL_YEAR = '/school-year'