export const BASE_URL = 'https://7b9d-158-140-182-97.ap.ngrok.io/annida'
export const REGISTER = '/registration'
export const MONITORING = '/monitoring/registration'
export const RELIGION = '/religion'
export const SCHOOL_YEAR = '/school-year'